# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93eeddd89249869b1b7a141a92624011f586a416e58f4df3996cda66ce699eb35ed72b160d32edbb190f47a334693d7f7e1a0fa7774cafa769e17d84c9c78e36

test:
  secret_key_base: d0b9c1b3aabb1e59ac22a56d69e3c16d8830421d7e9c3860b43983f797bf2566fe59e57f34cae0f5089a059733c8f1be23663fab7dd201bf3e1ac116a11c5775

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
